# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.

[package]
name = "lora_things_plus"
version.workspace = true
authors.workspace = true
edition.workspace = true
build = "../../build.rs"


[dependencies]
components = { path = "../../components" }
cortexm4 = { path = "../../../arch/cortex-m4" }
kernel = { path = "../../../kernel" }
apollo3 = { path = "../../../chips/apollo3" }

capsules-core = { path = "../../../capsules/core" }
capsules-extra = { path = "../../../capsules/extra" }
capsules-system = { path = "../../../capsules/system" }

[build-dependencies]
tock_build_scripts = { path = "../../build_scripts" }

[lints]
workspace = true

[features]
default = []

# This feature enables support for the ATECC508A Cryptographic Co-Processor
# Breakout. If you connect one of these
# (https://www.sparkfun.com/products/15573) via the I2C Qwiic connector you
# should enable this feature.
#
# NOTE: That the first time this is used it will lock the device, which
# can not be undone.
atecc508a = []
